export interface FondyCallback {
  rrn: string;
  masked_card: string;
  sender_cell_phone: string;
  sender_account: string;
  currency: string;
  fee: string;
  reversal_amount: string;
  settlement_amount: string;
  actual_amount: string;
  response_description: string;
  sender_email: string;
  order_status: string;
  response_status: string;
  order_time: string;
  actual_currency: string;
  order_id: string;
  tran_type: string;
  eci: string;
  settlement_date: string;
  payment_system: string;
  approval_code: string;
  merchant_id: string;
  settlement_currency: string;
  payment_id: string;
  card_bin: string;
  response_code: string;
  card_type: string;
  amount: string;
  signature: string;
  product_id: string;
  merchant_data: string;
  rectoken: string;
  rectoken_lifetime: string;
  verification_status: string;
  parent_order_id: string;
  additional_info: {
    capture_status: null | string;
    capture_amount: null | string;
    reservation_data: string;
    transaction_id: string;
    bank_response_code: null | string;
    bank_response_description: null | string;
    client_fee: string;
    settlement_fee: string;
    bank_name: string;
    bank_country: string;
    card_type: string;
    card_product: string;
    card_category: string;
    timeend: string;
    ipaddress_v4: string;
    payment_method: string;
    version_3ds: string;
    is_test: boolean;
  };
  response_signature_string: string;
}
