import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { getServerAuthSession } from "@/server/auth";
import { TRPCReactProvider } from "@/trpc/react";
import { UiProvider } from "@/app/_components/providers/UiProvider";
import { Body } from "@/app/_components/func/useTheme";
import { Bottom, ElementAnimation, Head } from "./_components/app/Layout";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
export const viewport = {
  //themeColor: "#FFFFFF",
  maximumScale: 1,
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <Body font={`font-sans ${inter.variable} `}>
        <TRPCReactProvider cookies={cookies().toString()} session={session}>
          <UiProvider>
            <div className="flex h-[100dvh] flex-col items-center justify-between">
              <Head />
              <ElementAnimation>{children}</ElementAnimation>
              <Bottom />
            </div>
          </UiProvider>
        </TRPCReactProvider>
      </Body>
    </html>
  );
}

//bg-gradient-to-tr from-fuchsia-300 to-cyan-300
